# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample08

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Table2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTable2(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Table2()
        x.Init(buf, n + offset)
        return x

    # Table2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Table2
    def Ifielda(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Table2
    def Ifieldb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Table2
    def Ifieldc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def Table2Start(builder): builder.StartObject(3)
def Table2AddIfielda(builder, ifielda): builder.PrependInt64Slot(0, ifielda, 0)
def Table2AddIfieldb(builder, ifieldb): builder.PrependInt64Slot(1, ifieldb, 0)
def Table2AddIfieldc(builder, ifieldc): builder.PrependInt64Slot(2, ifieldc, 0)
def Table2End(builder): return builder.EndObject()
