# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample155

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Struct1(object):
    __slots__ = ['_tab']

    # Struct1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Struct1
    def Sint32(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateStruct1(builder, sint32):
    builder.Prep(4, 4)
    builder.PrependInt32(sint32)
    return builder.Offset()
