# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample100

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Table3(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTable3(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Table3()
        x.Init(buf, n + offset)
        return x

    # Table3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Table3
    def Ifielda(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Table3Start(builder): builder.StartObject(1)
def Table3AddIfielda(builder, ifielda): builder.PrependInt32Slot(0, ifielda, 0)
def Table3End(builder): return builder.EndObject()
