# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample100

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Table2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTable2(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Table2()
        x.Init(buf, n + offset)
        return x

    # Table2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Table2
    def Table3a(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MySample.Sample100.Table3 import Table3
            obj = Table3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Table2
    def Table3aLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Table2
    def Table3aIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Table2Start(builder): builder.StartObject(1)
def Table2AddTable3a(builder, table3a): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(table3a), 0)
def Table2StartTable3aVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def Table2End(builder): return builder.EndObject()
