# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample154

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Struct1(object):
    __slots__ = ['_tab']

    # Struct1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Struct1
    def Struct2(self, obj, i):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0 + i * 4)
        return obj

    # Struct1
    def Struct2Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(0))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Struct1
    def Struct2IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(0))
        return o == 0


def CreateStruct1(builder, struct2_sint32):
    builder.Prep(4, 12)
    for _idx0 in range(3 , 0, -1):
        builder.Prep(4, 4)
        builder.PrependUint32(struct2_sint32[_idx0-1])
    return builder.Offset()
