# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample200

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Struct1(object):
    __slots__ = ['_tab']

    # Struct1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Struct1
    def Struct2(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj


def CreateStruct1(builder, struct2_sint32):
    builder.Prep(4, 4)
    builder.Prep(4, 4)
    builder.PrependInt32(struct2_sint32)
    return builder.Offset()
