test_name: 簡単なテスト

includes:
  - !include ../include/includes.yaml

marks:
  - parametrize:
      key: param_val_name
      vals:
        - user1
        # - user2

  - parametrize:
      key: param_val_age
      vals:
        - 20
        # - 30

stages:
  - name: HTTP レスポンスステータスコードのチェック
    # skip: True    # ステージ単位でのSkip
    request:
      url: http://127.0.0.1:5000/case1
      method: GET
    response:
      # HTTP レスポンスステータスコードで200が返る
      status_code: 200

  - name: HTTPレスポンス(json)のチェック(外部関数利用なし)
    # skip: True    # ステージ単位でのSkip
    request:
      url: http://127.0.0.1:5000/case1
      method: GET
    response:
      status_code: 200
      json:
        _id: !re_fullmatch "[-0-9a-z]+"
        index: !anything
        guid: !anything
        isActive: !anything
        balance: !anything
        picture: !anything
        # age: !anything
        age: !int "{var_age:d}"
        eyeColor: !anything
        # name: !anything
        name: !!str "{var_name:s}"
        gender: !anything
        company: !anything
        email: !anything
        phone: !anything
        address: !anything
        about: !anything
        registered: !anything
        latitude: !anything
        longitude: !anything
        tags: !anything
        friends: 
        - id: !anything
          etc: !anything

  - name: HTTPレスポンス(json)のチェック(外部関数利用あり)
    # skip: True    # ステージ単位でのSkip
    request:
      url: http://127.0.0.1:5000/case1
      method: GET
    response:
      status_code: 200
      verify_response_with:
        function: helper.testing_utils:is_specified_json
        extra_kwargs:
          schema: 
            name: "{var_name:s}"
            age: "{var_age:d}"

  - name: login
    skip: True    # ステージ単位でのSkip
    request:
      url: http://127.0.0.1:5000/case1
      method: GET
      headers:
        x-my-header: abc123
        $ext:
          function: helper.testing_utils:generate_bearer_token
      json:
        username: test_user
        password: abc123
    response:
      status_code: 200