# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample20

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Struct21(object):
    __slots__ = ['_tab']

    # Struct21
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Struct21
    def Bfielda21(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Struct21
    def Bfieldb21(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # Struct21
    def Bfieldc21(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateStruct21(builder, bfielda21, bfieldb21, bfieldc21):
    builder.Prep(1, 3)
    builder.PrependInt8(bfieldc21)
    builder.PrependInt8(bfieldb21)
    builder.PrependInt8(bfielda21)
    return builder.Offset()
