# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample20

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Struct1(object):
    __slots__ = ['_tab']

    # Struct1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Struct1
    def Ifielda1(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Struct1
    def Ifieldb1(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Struct1
    def Ifieldc1(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Struct1
    def Struct21(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj

    # Struct1
    def Struct22(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 16)
        return obj


def CreateStruct1(builder, ifielda1, ifieldb1, ifieldc1, struct21_bfielda21, struct21_bfieldb21, struct21_bfieldc21, struct22_ifielda22, struct22_ifieldb22, struct22_ifieldc22):
    builder.Prep(4, 28)
    builder.Prep(4, 12)
    builder.PrependInt32(struct22_ifieldc22)
    builder.PrependInt32(struct22_ifieldb22)
    builder.PrependInt32(struct22_ifielda22)
    builder.Pad(1)
    builder.Prep(1, 3)
    builder.PrependInt8(struct21_bfieldc21)
    builder.PrependInt8(struct21_bfieldb21)
    builder.PrependInt8(struct21_bfielda21)
    builder.PrependInt32(ifieldc1)
    builder.PrependInt32(ifieldb1)
    builder.PrependInt32(ifielda1)
    return builder.Offset()
