# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample20

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Struct22(object):
    __slots__ = ['_tab']

    # Struct22
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Struct22
    def Ifielda22(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Struct22
    def Ifieldb22(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Struct22
    def Ifieldc22(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateStruct22(builder, ifielda22, ifieldb22, ifieldc22):
    builder.Prep(4, 12)
    builder.PrependInt32(ifieldc22)
    builder.PrependInt32(ifieldb22)
    builder.PrependInt32(ifielda22)
    return builder.Offset()
