search_conditions:
  - condition:
    target_file:
      - "*_test_*.log"
      - "*_test_*.txt"
    output_file: output_a.txt
    keywords:
      literal:
        - ".*test_str_a"
        - ".*test_str_b"
      regex:
        - ".*test_str_a"
        - ".*test_str_b"
  - condition:
    target_file:
      - "*_sample_*.log"
      - "*_sample_*.txt"
    output_file: output_b.txt
    keywords:
      literal:
        - ".*sample_str_a"
        - ".*sample_str_b"
      regex:
        - ".*sample_str_a"
        - ".*sample_str_b"
