test_name: レスポンスの一部変数保存

includes:
  - !include ../include/includes.yaml

stages:
  - name: HTTPレスポンス(_id)を変数(_id)に保存する
    # skip: True    # ステージ単位でのSkip
    request:
      url: http://127.0.0.1:5000/case1
      method: GET
    response:
      status_code: 200
      save:
        json:
          # 変数保存(次のStageで使用可能)
          save_id: "_id"

  - name: 保存した変数(_id)を使用する
    # skip: True    # ステージ単位でのSkip
    request:
      url: http://127.0.0.1:5000/case1
      method: GET
    response:
      status_code: 200
      verify_response_with:
        function: helper.testing_utils:disp_response
        extra_kwargs:
          # 変数利用
          _id: "{save_id:s}"

