# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SmartCamera

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ObjectDetectionData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObjectDetectionData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjectDetectionData()
        x.Init(buf, n + offset)
        return x

    # ObjectDetectionData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObjectDetectionData
    def ObjectDetectionList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from SmartCamera.GeneralObject import GeneralObject
            obj = GeneralObject()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjectDetectionData
    def ObjectDetectionListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ObjectDetectionData
    def ObjectDetectionListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ObjectDetectionDataStart(builder): builder.StartObject(1)
def ObjectDetectionDataAddObjectDetectionList(builder, objectDetectionList): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objectDetectionList), 0)
def ObjectDetectionDataStartObjectDetectionListVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ObjectDetectionDataEnd(builder): return builder.EndObject()
