# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SmartCamera

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ObjectDetectionTop(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsObjectDetectionTop(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjectDetectionTop()
        x.Init(buf, n + offset)
        return x

    # ObjectDetectionTop
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObjectDetectionTop
    def Perception(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from SmartCamera.ObjectDetectionData import ObjectDetectionData
            obj = ObjectDetectionData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ObjectDetectionTopStart(builder): builder.StartObject(1)
def ObjectDetectionTopAddPerception(builder, perception): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(perception), 0)
def ObjectDetectionTopEnd(builder): return builder.EndObject()
