# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample04

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Struct1(object):
    __slots__ = ['_tab']

    # Struct1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Struct1
    def Ifielda(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Struct1
    def Ifieldb(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Struct1
    def Ifieldc(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateStruct1(builder, ifielda, ifieldb, ifieldc):
    builder.Prep(4, 12)
    builder.PrependInt32(ifieldc)
    builder.PrependInt32(ifieldb)
    builder.PrependInt32(ifielda)
    return builder.Offset()
