# 辞書スキーマの詳細
# https://docs.python.org/ja/3/library/logging.config.html#dictionary-schema-details
version: 1
formatters:
  simple:
    format: "%(asctime)s [%(levelname)s]: (%(name)s:%(lineno)d) %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    # logging.handlers.RotatingFileHandler は
    # ログファイルが指定されたサイズに達したときに新しいログファイルを作成し、
    # 古いログファイルをローテーション（回転）させるためのハンドラ
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logconfig.log
    maxBytes: 16
    backupCount: 3
# [loggers] logging.getLogger()で名前 simpleExample を指定した時に使用される設定
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console,file]
    propagate: no
# [root] logging.getLogger()で名前を指定しない、
# もしくは[loggers]で定義した名前以外のものを指定した時(root logger)に使用される設定
root:
  level: INFO
  handlers: [console]