# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample10

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TopTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTopTable(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TopTable()
        x.Init(buf, n + offset)
        return x

    # TopTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TopTable
    def Ifielda(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 100

    # TopTable
    def Ifieldb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 200

def TopTableStart(builder): builder.StartObject(2)
def TopTableAddIfielda(builder, ifielda): builder.PrependInt32Slot(0, ifielda, 100)
def TopTableAddIfieldb(builder, ifieldb): builder.PrependInt32Slot(1, ifieldb, 200)
def TopTableEnd(builder): return builder.EndObject()
