# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample202

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Table2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Table2()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTable2(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Table2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Table2
    def Sint32(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Table2Start(builder):
    builder.StartObject(1)

def Start(builder):
    Table2Start(builder)

def Table2AddSint32(builder, sint32):
    builder.PrependInt32Slot(0, sint32, 0)

def AddSint32(builder, sint32):
    Table2AddSint32(builder, sint32)

def Table2End(builder):
    return builder.EndObject()

def End(builder):
    return Table2End(builder)
