# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample102

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Table2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTable2(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Table2()
        x.Init(buf, n + offset)
        return x

    # Table2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Table2
    def Struct3a(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            from MySample.Sample102.Struct3 import Struct3
            obj = Struct3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Table2
    def Struct3aLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Table2
    def Struct3aIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Table2Start(builder): builder.StartObject(1)
def Table2AddStruct3a(builder, struct3a): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(struct3a), 0)
def Table2StartStruct3aVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def Table2End(builder): return builder.EndObject()
