# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample50

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Struct1(object):
    __slots__ = ['_tab']

    # Struct1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Struct1
    def Ifielda(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Struct1
    def Colora(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateStruct1(builder, ifielda, colora):
    builder.Prep(4, 8)
    builder.Pad(3)
    builder.PrependInt8(colora)
    builder.PrependInt32(ifielda)
    return builder.Offset()
