# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Sample50

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TopTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTopTable(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TopTable()
        x.Init(buf, n + offset)
        return x

    # TopTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TopTable
    def Tablea(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MySample.Sample50.Table1 import Table1
            obj = Table1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TopTable
    def Tableb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MySample.Sample50.Table1 import Table1
            obj = Table1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TopTable
    def Structa(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from MySample.Sample50.Struct1 import Struct1
            obj = Struct1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TopTable
    def Structb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from MySample.Sample50.Struct1 import Struct1
            obj = Struct1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TopTableStart(builder): builder.StartObject(4)
def TopTableAddTablea(builder, tablea): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tablea), 0)
def TopTableAddTableb(builder, tableb): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tableb), 0)
def TopTableAddStructa(builder, structa): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(structa), 0)
def TopTableAddStructb(builder, structb): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(structb), 0)
def TopTableEnd(builder): return builder.EndObject()
